version: '3.4'

services:
  awswebapi:
    container_name: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - localstackUri=http://localstack:4566
      - localstackRegion=us-east-1
      - localstackAccountId=000000000000
    ports:
      - "5000:80"
    volumes:
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
  localstack:
    image: localstack/localstack
    container_name: localstack
    hostname: localstack
    ports:
      - "4566:4566"
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 1024M
    environment:
      - SERVICES=sns,sqs,cloudwatch,s3,ssm,logs
      - PORT_WEB_UI=8080
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR},
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  sql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sql
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=SAPassword123!
      - ACCEPT_EULA=Y
      - TZ=Europe/London